#!/bin/sh

# Set these paths appropriately

BIN=modules/DutchWSD/TreeTagger/bin
CMD=modules/DutchWSD/TreeTagger/cmd
LIB=modules/DutchWSD/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
